# Generated by Django 5.2.4 on 2025-07-30 16:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaine',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poste',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
