# Generated by Django 5.2.4 on 2025-08-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_service', '0002_stage_deleted_stage_deleted_at_stage_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='demande_de_stage',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='signature_chef_departement',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='signature_encadrant',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='signature_responsable_RH',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='statut',
            field=models.CharField(choices=[('annule', 'Annulé'), ('en_attente_depot_dossier', 'En attente de dépôt de dossier'), ('expire', 'Expiré'), ('en_attente_visite_medicale', 'En attente de visite médicale'), ('en_attente_des_signatures', 'En attente de signatures'), ('stage_en_cours', 'Stage en cours'), ('en_attente_depot_rapport', 'En attente de dépôt de rapport'), ('en_attente_signature_du_rapport_par_l_encadrant', "En attente de signature du rapport par l'encadrant"), ('termine', 'Terminé')], default='en_attente_depot_dossier', max_length=50),
        ),
    ]
