# Generated by Django 5.2.4 on 2025-07-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_service', '0002_domaine_date_creation_alter_poste_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaine',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='poste',
            name='titre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
