# Generated by Django 5.2.4 on 2025-07-30 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_service', '0003_alter_domaine_nom_alter_poste_titre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poste',
            name='domaine',
        ),
        migrations.AddField(
            model_name='poste',
            name='domaine',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poste', to='resume_service.domaine'),
        ),
    ]
