# Generated by Django 5.2.4 on 2025-08-31 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_service', '0004_sujet_created_at_sujet_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='prolongation',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
