# Generated by Django 5.2.4 on 2025-07-30 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_service', '0004_remove_poste_domaine_poste_domaine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='date_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 29, 18, 32, 40, 567082), null=True),
        ),
    ]
