# Generated by Django 5.2.4 on 2025-07-30 18:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_service', '0005_alter_poste_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='date_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 29, 19, 7, 57, 616339), null=True),
        ),
        migrations.AlterField(
            model_name='poste',
            name='domaine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poste', to='resume_service.domaine'),
        ),
    ]
