# Generated by Django 5.2.4 on 2025-09-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_service', '0005_alter_stage_nature_alter_stage_prolongation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='nature',
            field=models.CharField(choices=[('stage_observation', "Stage d'observation"), ('stage_application', "Stage d'application"), ('pfe', 'PFE')], default='stage_observation', max_length=50),
        ),
    ]
