# Generated by Django 5.2.4 on 2025-07-31 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_service', '0006_alter_poste_date_expiration_alter_poste_domaine'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='extracted_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='poste',
            name='date_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 30, 2, 0, 11, 574262), null=True),
        ),
    ]
