# Generated by Django 5.2.4 on 2025-09-13 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_service', '0006_alter_stage_nature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiaire',
            name='introduit_par',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stagiaires_introduits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stagiaires_deleted', to=settings.AUTH_USER_MODEL),
        ),
    ]
