# Generated by Django 5.2.4 on 2025-09-13 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_service', '0007_stagiaire_introduit_par_alter_stagiaire_deleted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagiaire',
            name='introduit_par',
        ),
        migrations.AddField(
            model_name='stage',
            name='introduit_par',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stagiaires_introduits', to=settings.AUTH_USER_MODEL),
        ),
    ]
