# Generated by Django 5.2.4 on 2025-08-06 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_service', '0007_candidature_extracted_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='date_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 9, 5, 19, 36, 12, 903065), null=True),
        ),
    ]
