# Generated by Django 5.2.4 on 2025-08-12 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_service', '0008_alter_poste_date_expiration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidature',
            name='candidat',
        ),
        migrations.RemoveField(
            model_name='candidature',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='domaine',
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('num_tel', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('num_cin', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nature', models.CharField(choices=[('stage', 'Stage'), ('pfe', 'PFE'), ('alternance', 'Alternance')], max_length=50)),
                ('date_candidature', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('en_attente_depot_dossier', 'En attente de dépôt de dossier'), ('expire', 'Expiré'), ('en_attente_visite_medicale', 'En attente de visite médicale'), ('en_attente_signature_de_l_encadrant', "En attente de signature de l'encadrant"), ('en_attente_signature_du_responsable_RH', 'En attente de signature du responsable RH'), ('en_attente_signature_du_stagiaire', 'En attente de signature du stagiaire'), ('stage_en_cours', 'Stage en cours')], default='en_attente', max_length=50)),
                ('convention', models.BinaryField(blank=True, null=True)),
                ('assurance', models.BinaryField(blank=True, null=True)),
                ('lettre_motivation', models.BinaryField(blank=True, null=True)),
                ('cv', models.BinaryField(blank=True, null=True)),
                ('cin', models.BinaryField(blank=True, null=True)),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='resume_service.stagiaire')),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='resume_service.sujet')),
            ],
        ),
        migrations.DeleteModel(
            name='Candidat',
        ),
        migrations.DeleteModel(
            name='Candidature',
        ),
        migrations.DeleteModel(
            name='Domaine',
        ),
        migrations.DeleteModel(
            name='Poste',
        ),
    ]
