# Generated by Django 5.2.4 on 2025-09-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_service', '0009_stage_chef_departement_stage_encadrant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='chef_departement',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='encadrant',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='responsable_RH',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='signature_chef_departement',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='signature_encadrant',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='signature_responsable_RH',
        ),
        migrations.AddField(
            model_name='stage',
            name='demande_de_stage_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
