# Generated by Django 5.2.4 on 2025-08-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_service', '0010_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='cin',
        ),
        migrations.RemoveField(
            model_name='stagiaire',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stagiaire',
            name='num_cin',
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='cin',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='matricule',
            field=models.CharField(default='', max_length=8, primary_key=True, serialize=False),
        ),
    ]
