# Generated by Django 5.2.4 on 2025-09-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_service', '0010_remove_stage_chef_departement_remove_stage_encadrant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='demande_de_stage_pdf',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
