# Generated by Django 5.2.4 on 2025-08-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_service', '0011_remove_stage_cin_remove_stagiaire_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
