# Generated by Django 5.2.4 on 2025-08-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=256)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(blank=True, max_length=256, null=True)),
                ('validite_token', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('hr_manager', 'Responsable RH'), ('hr_user', 'Utilisateur RH')], default='hr_user', max_length=50)),
            ],
        ),
    ]
