# Generated by Django 5.2.4 on 2025-08-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='departement',
            field=models.CharField(blank=True, choices=[('digital_factory', 'Digital Factory'), ('ressources_humaines', 'Ressources Humaines'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('maintenance', 'Maintenance')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('admin_rh', 'Admin RH'), ('utilisateur_rh', 'Utilisateur RH'), ('utilisateur', 'Utilisateur')], default='utilisateur_rh', max_length=50),
        ),
    ]
