# Generated by Django 5.2.4 on 2025-09-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0003_utilisateur_capacite_utilisateur_capacite_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='capacite_cache_restante',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='capacite_restante',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='capacite',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='capacite_cache',
            field=models.IntegerField(default=2),
        ),
    ]
