# Generated by Django 5.2.4 on 2025-09-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0004_utilisateur_capacite_cache_restante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('admin_rh', 'Admin RH'), ('utilisateur_rh', 'Utilisateur RH'), ('utilisateur', 'Utilisateur'), ('responsable_de_service', 'Responsable de Service')], default='utilisateur_rh', max_length=50),
        ),
    ]
